### ISSUE TITLE
Backup Restore function

### ISSUE THREAD

**Issue by anuraag488** [ikws4/WeiJu2#14]
Hi
Please add Backup Restore function.

Thanks

**Comment by anuraag488** [comment]
@ikws4 
Restore not working.
I did

Created a script
Backup
Remove script
Attempt restore.
Restart App but script not visible.

**Comment by ikws4** [comment]
fixed

**Comment by anuraag488** [comment]
Working. I need to modify json data where **io.ikws4.weiju** key contains array of script names to restore my created scripts.

So for new backups it will work fine.
