### ISSUE TITLE
Possibility to change colors of webapps

### ISSUE THREAD

**Issue by xerta555** [ikws4/WeiJu2#7]
Hi

I am following up on my request [here](https://forum.xda-developers.com/t/app-xposed-7-0-weiju2-scriptable-xposed-module.4482585/post-87346161).
Were you able to get or do you have any idea to get a version of your module to be able to change the CSS properties of webapps like Teams, Skype, Instagram, Messenger, Twitter, Discord etc?

Thanks in advance.

**Comment by ikws4** [comment]
It seems none of the apps you listed are WebView based, I've already checked Discord it's a native android app.

**Comment by xerta555** [comment]
Ok, and do you think that it's possible to make works theses two ways ?

**Comment by ikws4** [comment]
For app like `Forem` and `Notion` are just a wrapper of Webview, so it can be done with this method. But for Discord and other react-native based apps, there is no way to do it, since there are no css and DOM after compilation.

**Comment by xerta555** [comment]
> For app like `Forem` and `Notion` are just a wrapper of Webview, so it can be done with this method. But for Discord and other react-native based apps, there is no way to do it, since there are no css and DOM after compilation.

Ok, and it already works with your app ?

**Comment by ikws4** [comment]
Yeah, it works pretty well!

<div>
<img src="https://user-images.githubusercontent.com/47056144/190412773-895f0568-d707-41ac-a95d-da55e5d980db.png" width=25%/>
<img src="https://user-images.githubusercontent.com/47056144/190412704-2b12bb8e-2869-48dd-925c-465d1c6494ea.png" width=25%/>
</div>

**Comment by xerta555** [comment]
> Yeah, it works pretty well!
> <img alt="" width="25%/" src="https://user-images.githubusercontent.com/47056144/190412773-895f0568-d707-41ac-a95d-da55e5d980db.png"> <img alt="" width="25%/" src="https://user-images.githubusercontent.com/47056144/190412704-2b12bb8e-2869-48dd-925c-465d1c6494ea.png">

Very nice!

Is it possible to directly load a CSS file which could be stored in a folder, for exemple, in `/data/adb/module/module-name-for-WeiJu2\my-css-file.css` ?

**Comment by ikws4** [comment]
Since file access become more and more restricted these day on Android, I don't recommend using files. Instead, you should put styles inside the `css` field.

**Comment by xerta555** [comment]
> Since file access become more and more restricted these day on Android, I don't recommend using files. Instead, you should put styles inside the `css` field.

It's right that we can do an huge copy-past in your app if we want..

**Comment by xerta555** [comment]
I did the test with the following applications, and the modification of text sequences did not work on any of them:
- Messenger
- Instagram
- Github
- Opera Beta
- Firefox
- Twitter

How could we know easily if an app use Webview and so that it's possible to use your module on it with an CSS rule(s) ?

**Comment by ikws4** [comment]
```lua
local WebView = import("android.webkit.WebView")
local Context = import("android.content.Context")
local AttributeSet = import("android.util.AttributeSet")
local Toast = import("android.widget.Toast")

hook {
  class = WebView,
  params = {
    Context,
    AttributSet,
    int,
  },
  after = function(this, params)
    local context = params[1]
    Toast:makeText(context, "WebView Initialized", Toast.LENGTH_SHORT):show()
  end,
}
```

The script will inform you when an WebView was created.

**Comment by xerta555** [comment]
None of the applications I use work with WebView.
Good work though.

**Comment by xerta555** [comment]
> ```lua
> local WebView = import("android.webkit.WebView")
> local Context = import("android.content.Context")
> local AttributeSet = import("android.util.AttributeSet")
> local Toast = import("android.widget.Toast")
> 
> hook {
>   class = WebView,
>   params = {
>     Context,
>     AttributSet,
>     int,
>   },
>   after = function(this, params)
>     local context = params[1]
>     Toast:makeText(context, "WebView Initialized", Toast.LENGTH_SHORT):show()
>   end,
> }
> ```
> 
> The script will inform you when an WebView was created.

I try your script for a new app that i use for test but apparently it don't works/save
![Screenshot_20221215-200829.jpg](https://user-images.githubusercontent.com/20888017/207946552-62d25107-1da3-46dd-a4bc-8f6545c48e29.jpg)

Any idea

**Comment by ikws4** [comment]
You need add a metadata in front of the script.

E.g.
```lua
--[=[
@metadata
  return {
    name = "more_teach_hot",
    author = "character",
    version = "0.0.1",
    description = "branch dollar experiment proper gave tire pay month yard spot",
    example = [[
      require("character.more_teach_hot").setup {
        
      }
    ]]
  }
@end
--]=]
```
